import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { completeTailEvents, proveValidationTurn } from '../scripts/r2.8-validation-turn-proof.mjs';
const model = '@cf/meta/llama-3.3-70b-instruct-fp8-fast';
const rooms = ['101','102','103'].map((roomNumber,i)=>({roomNumber,id:`00000000-0000-0000-0000-00000000000${i+1}`}));
const setup = {sessionId:'session',data:{source:'hms',truth:'transactional',start:'2030-01-01',end:'2030-01-03',requestedGuests:4,rooms},message:'Disponibles: 101 y 102.'};
function run(script, responses) {
 const dir=mkdtempSync(join(tmpdir(),'r284-offline-')); const tail=join(dir,'tail'), calls=join(dir,'calls');
 writeFileSync(tail,'');
 writeFileSync(join(dir,'mock.mjs'), `import {appendFileSync} from 'node:fs'; const responses=${JSON.stringify(responses)}; let n=0; globalThis.fetch=async(url,options)=>{appendFileSync(${JSON.stringify(calls)},JSON.stringify({url,body:JSON.parse(options.body)})+'\\n'); const r=responses[n++]; if(!r) throw Error('unexpected extra provider request'); appendFileSync(${JSON.stringify(tail)},JSON.stringify({truncated:false,outcome:'ok',event:{request:{headers:{'x-request-id':options.headers['x-request-id']}}},logs:[{message:[JSON.stringify({kind:'model_inference',label:'agent_core_route',sessionId:r.body.sessionId,model:${JSON.stringify(model)}})]}]})+'\\n'); return new Response(JSON.stringify(r.body),{status:r.status??200});};`);
 try { const result=spawnSync(process.execPath,['--import',join(dir,'mock.mjs'),script],{encoding:'utf8',env:{...process.env,AI_COMMERCE_STAGING_URL:'https://offline.invalid',R28_TAIL_PATH:tail}}); return {code:result.status,report:JSON.parse(result.stdout),calls:readFileSync(calls,'utf8').trim().split('\n').map(JSON.parse)}; } finally {rmSync(dir,{recursive:true,force:true});}
}
test('dialogue stops after invalid C06 and preserves partial evidence',()=>{const r=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:{...setup,data:{...setup.data,requestedGuests:3}}}]);assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.equal(r.report.results[0].pass,false);assert.equal(r.report.transcript.length,1);});
test('C07 cannot be rescued with extra confirmation',()=>{const r=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},{body:{sessionId:'session',message:'Entendido.'}}]);assert.equal(r.code,1);assert.equal(r.calls.length,2);});
test('corpus stops after invalid availability before intent or next case',()=>{const r=run('scripts/r2.8.4-llm-language-corpus.mjs',[{body:setup}]);assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.equal(r.report.transcript.length,1);assert.match(r.report.transcript[0].failure,/setup/);});
test('completed envelopes: fallback and missing telemetry fail closed',async()=>{const dir=mkdtempSync(join(tmpdir(),'r284-tail-'));const path=join(dir,'tail');try { const envelope={truncated:false,outcome:'ok',event:{request:{headers:{'x-request-id':'rid'}}},logs:[{message:[JSON.stringify({kind:'model_fallback',sessionId:'sid',label:'agent_core_route'})]}]};writeFileSync(path,'PTY metadata\n'+JSON.stringify(envelope,null,2));assert.equal(completeTailEvents(readFileSync(path,'utf8')).length,1);await assert.rejects(proveValidationTurn('rid','sid',{path,timeoutMs:1}),/fallback/);await assert.rejects(proveValidationTurn('missing','sid',{path,timeoutMs:1}),/UNKNOWN/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('manual workflow and corpus sequence are guarded',()=>{const workflow=readFileSync('.github/workflows/r2.8-multi-room-dialogue.yml','utf8');assert.doesNotMatch(workflow,/^  push:/m);assert.match(workflow,/if: github.event_name == 'workflow_dispatch'/);assert.match(workflow,/if \[\[ "\$code" -ne 0 \]\]; then[\s\S]*?exit 0[\s\S]*?node scripts\/r2.8.4-llm-language-corpus/);});
function boundary(overrides={}) { const ids=rooms.slice(0,2).map(x=>x.id);return {status:409,body:{sessionId:'session',error:{code:'APPROVAL_REQUIRED'},approvalToken:'unconsumed-test',approvalSummary:`Confirmar ${ids.join(', ')} del 2030-01-01 al 2030-01-03.`,approvalPlan:{toolId:'hms.createMultiReservation',input:{roomIds:ids,checkIn:'2030-01-01',checkOut:'2030-01-03'}},approvalContext:{stay:{checkIn:'2030-01-01',checkOut:'2030-01-03',guests:4},selectedRoomIds:ids,roomOccupancy:[]},...overrides}}; }
test('exact C07 HITL completes in two turns and wrong final guests fails',()=>{const ok=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},boundary()]);assert.equal(ok.code,0);assert.equal(ok.calls.length,2);const wrong=boundary();wrong.body.approvalContext.stay.guests=2;const bad=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},wrong]);assert.equal(bad.code,1);assert.equal(bad.calls.length,2);});
test('only natural occupancy clarification permits a third turn, requiring 2+2',()=>{const request={body:{sessionId:'session',message:'¿Cómo distribuimos la ocupación en cada habitación?',outcome:'clarification',missing:['occupancy']}};const final=boundary();final.body.approvalContext.roomOccupancy=rooms.slice(0,2).map(x=>({roomId:x.id,guests:2}));const ok=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},request,final]);assert.equal(ok.code,0);assert.equal(ok.calls.length,3);assert.equal(ok.calls[2].body.message,'Dos en cada habitación.');const bad=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},request,boundary()]);assert.equal(bad.code,1);assert.equal(bad.calls.length,3);});
