import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { completeTailEvents, proveValidationTurn, telemetry } from '../scripts/r2.8-validation-turn-proof.mjs';
import corpus from './fixtures/r2.8.4-llm-language-corpus.json' with { type: 'json' };
const model = '@cf/meta/llama-3.3-70b-instruct-fp8-fast';
const rooms = ['101','102','103'].map((roomNumber,i)=>({roomNumber,id:`00000000-0000-0000-0000-00000000000${i+1}`}));
const setup = {sessionId:'session',data:{source:'hms',truth:'transactional',start:'2030-01-01',end:'2030-01-03',requestedGuests:4,rooms},message:'Disponibles: 101 y 102.'};
function run(script, responses, { tailProof = true, tailPathMode = 'file', tailRouteKind = 'model_inference', tailScriptVersionId, versionId, directRoute = 'baseline_llm' } = {}) {
  const dir=mkdtempSync(join(tmpdir(),'r284-offline-')); const tail=join(dir,'tail'), calls=join(dir,'calls');
  if(tailPathMode==='file') writeFileSync(tail,'');
  if(tailPathMode==='corrupt') writeFileSync(tail,'{"broken": nope}');
  if(tailPathMode==='incomplete') writeFileSync(tail,'{"broken":');
  const tailPath=tailPathMode==='unreadable'?dir:tailPathMode==='missing'?join(dir,'missing-tail'):tail;
  writeFileSync(join(dir,'mock.mjs'), `import {appendFileSync} from 'node:fs'; const responses=${JSON.stringify(responses)}; const tailProof=${JSON.stringify(tailProof)}, tailRouteKind=${JSON.stringify(tailRouteKind)}, tailScriptVersionId=${JSON.stringify(tailScriptVersionId)}, directRoute=${JSON.stringify(directRoute)}; let n=0; globalThis.fetch=async(url,options)=>{appendFileSync(${JSON.stringify(calls)},JSON.stringify({url,body:JSON.parse(options.body)})+'\\n'); const r=responses[n++]; if(!r) throw Error('unexpected extra provider request'); if(tailProof)appendFileSync(${JSON.stringify(tail)},JSON.stringify({truncated:false,outcome:'ok',...(tailScriptVersionId?{scriptVersion:{id:tailScriptVersionId}}:{}),event:{request:{headers:{'x-request-id':options.headers['x-request-id']}}},logs:[{message:[JSON.stringify({kind:tailRouteKind,label:'agent_core_route',sessionId:r.body.sessionId,model:${JSON.stringify(model)}})]}]})+'\\n'); return new Response(JSON.stringify({...(r.body??{}),...(directRoute?{validationRouteProvenance:{route:directRoute}}:{})}),{status:r.status??200,headers:${JSON.stringify(versionId)}?{'x-acp-validation-runtime-version':${JSON.stringify(versionId)}}:{}});};`);
  try { const env={...process.env,AI_COMMERCE_STAGING_URL:'https://offline.invalid'}; if(tailProof || tailPathMode!=='file') env.R28_TAIL_PATH=tailPath; else delete env.R28_TAIL_PATH; if(versionId) env.R28_VERSION_ID=versionId; else delete env.R28_VERSION_ID; const result=spawnSync(process.execPath,['--import',join(dir,'mock.mjs'),script],{encoding:'utf8',env}); return {code:result.status,report:JSON.parse(result.stdout),calls:readFileSync(calls,'utf8').trim().split('\n').map(JSON.parse)}; } finally {rmSync(dir,{recursive:true,force:true});}
}
function runTelemetryCounter(script, raw, { versionId } = {}) {
  const dir=mkdtempSync(join(tmpdir(),'r284-counter-')); const tail=join(dir,'tail');
  try { writeFileSync(tail,raw); const result=spawnSync(process.execPath,[script,tail],{encoding:'utf8',env:{...process.env,...(versionId?{R28_VERSION_ID:versionId}:{})}}); return result; }
  finally { rmSync(dir,{recursive:true,force:true}); }
}
test('dialogue stops after invalid C06 and preserves partial evidence',()=>{const r=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:{...setup,data:{...setup.data,requestedGuests:3}}}]);assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.equal(r.report.results[0].pass,false);assert.equal(r.report.transcript.length,1);});
test('C07 cannot be rescued with extra confirmation',()=>{const r=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},{body:{sessionId:'session',message:'Entendido.'}}]);assert.equal(r.code,1);assert.equal(r.calls.length,2);});
test('corpus stops after invalid availability before intent or next case',()=>{const r=run('scripts/r2.8.4-llm-language-corpus.mjs',[{body:setup}]);assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.equal(r.report.transcript.length,1);assert.match(r.report.transcript[0].failure,/setup/);});
test('captured fallback fails closed and a missing request remains unknown',async()=>{const dir=mkdtempSync(join(tmpdir(),'r284-tail-'));const path=join(dir,'tail');try { const envelope={truncated:false,outcome:'ok',event:{request:{headers:{'x-request-id':'rid'}}},logs:[{message:[JSON.stringify({kind:'model_fallback',sessionId:'sid',label:'agent_core_route'})]}]};writeFileSync(path,'PTY metadata\n'+JSON.stringify(envelope,null,2));assert.equal(completeTailEvents(readFileSync(path,'utf8')).length,1);await assert.rejects(proveValidationTurn('rid','sid',{path,timeoutMs:1}),/fallback/);await assert.rejects(proveValidationTurn('missing','sid',{path,timeoutMs:1}),/UNKNOWN/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('captured human approval confirmation audit is CAPTURED_INVALID while allowed reads remain valid',async()=>{const dir=mkdtempSync(join(tmpdir(),'r284-tail-'));const path=join(dir,'tail');const route={kind:'model_inference',sessionId:'sid',label:'agent_core_route',model};const audit={kind:'audit_event',timestamp:'2030-01-01T00:00:00.000Z',requestId:'rid',tenantId:'tenant',actorId:'actor',sessionId:'sid',toolId:'hms.createReservation',status:'allowed',detail:'human_approval_confirmed:human_confirmation_required'};try { const envelope={truncated:false,outcome:'ok',event:{request:{headers:{'x-request-id':'rid'}}},logs:[{message:[JSON.stringify(route),JSON.stringify(audit)]}]};writeFileSync(path,JSON.stringify(envelope));await assert.rejects(proveValidationTurn('rid','sid',{path,timeoutMs:1}),/unauthorized mutation or approval activity/);audit.toolId='hms.getAvailability';envelope.logs[0].message[1]=JSON.stringify(audit);writeFileSync(path,JSON.stringify(envelope));await proveValidationTurn('rid','sid',{path,timeoutMs:1});}finally{rmSync(dir,{recursive:true,force:true});}});
test('telemetry parser distinguishes ordinary brace strings from captured telemetry',()=>{
  assert.deepEqual(telemetry(['{not telemetry}', '[ordinary bracket text]']), []);
  const inference={kind:'model_inference',sessionId:'sid',label:'agent_core_route',model};
  const audit={kind:'audit_event',sessionId:'sid',toolId:'hms.createReservation',status:'approval_required'};
  assert.deepEqual(telemetry(JSON.stringify(JSON.stringify(inference))), [inference]);
  assert.deepEqual(telemetry(['ordinary {brace} prose', JSON.stringify({outer:[JSON.stringify(audit)]})]), [audit]);
  assert.throws(()=>telemetry('{"kind":"model_inference"'),/CAPTURED_INVALID.*malformed captured telemetry JSON/);
  assert.throws(()=>completeTailEvents('{"truncated":false'),/CAPTURED_INVALID.*incomplete tail event/);
  assert.throws(()=>completeTailEvents('{"broken": nope}'),/CAPTURED_INVALID.*malformed tail event/);
});
test('absent route telemetry is unknown, while malformed capture remains invalid',async()=>{const dir=mkdtempSync(join(tmpdir(),'r284-tail-'));const corrupt=join(dir,'corrupt');const routeFree=join(dir,'route-free');const malformedLog=join(dir,'malformed-log');try {writeFileSync(corrupt,'{"broken": nope}');writeFileSync(routeFree,JSON.stringify({truncated:false,outcome:'ok',event:{request:{headers:{'x-request-id':'rid'}}},logs:[]}));writeFileSync(malformedLog,JSON.stringify({truncated:false,outcome:'ok',event:{request:{headers:{'x-request-id':'rid'}}},logs:[{message:['{"kind":"model_inference"']}]}));assert.throws(()=>completeTailEvents(readFileSync(corrupt,'utf8')),/CAPTURED_INVALID/);await assert.rejects(proveValidationTurn('rid','sid',{timeoutMs:1}),/UNKNOWN/);await assert.rejects(proveValidationTurn('rid','sid',{path:join(dir,'missing'),timeoutMs:1}),/UNKNOWN/);await assert.rejects(proveValidationTurn('rid','sid',{path:routeFree,timeoutMs:1}),/UNKNOWN.*no captured baseline route inference/);await assert.rejects(proveValidationTurn('rid','sid',{path:malformedLog,timeoutMs:1}),/CAPTURED_INVALID.*malformed captured telemetry JSON/);await assert.rejects(proveValidationTurn('rid','sid',{path:dir,timeoutMs:1}),/CAPTURED_INVALID/);writeFileSync(join(dir,'incomplete'),'{"broken":');await assert.rejects(proveValidationTurn('rid','sid',{path:join(dir,'incomplete'),timeoutMs:1}),/CAPTURED_INVALID/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('captured malformed telemetry logs and wrong-version aggregate envelopes fail closed',()=>{const valid={truncated:false,outcome:'ok',scriptVersion:{id:'expected-version'},event:{request:{headers:{}}},logs:[{message:['{"kind":"model_inference"']}]};for(const script of ['scripts/count-model-telemetry.mjs','scripts/count-audit-events.mjs']){const malformed=runTelemetryCounter(script,JSON.stringify(valid));assert.notEqual(malformed.status,0);assert.match(malformed.stderr,/CAPTURED_INVALID/);for(const envelope of [{...valid,scriptVersion:{id:'wrong-version'}},{...valid,scriptVersion:{id:'wrong-version'},event:undefined}]){const wrongVersion=runTelemetryCounter(script,JSON.stringify(envelope),{versionId:'expected-version'});assert.notEqual(wrongVersion.status,0);assert.match(wrongVersion.stderr,/CAPTURED_INVALID.*Version mismatch/);}}});
test('manual workflow and corpus sequence are guarded',()=>{const workflow=readFileSync('.github/workflows/r2.8-multi-room-dialogue.yml','utf8');assert.doesNotMatch(workflow,/^  push:/m);assert.match(workflow,/if: github.event_name == 'workflow_dispatch'/);assert.match(workflow,/if \[\[ "\$code" -ne 0 \]\]; then[\s\S]*?exit 0[\s\S]*?node scripts\/r2.8.4-llm-language-corpus/);});
function boundary(overrides={}) { const ids=rooms.slice(0,2).map(x=>x.id);return {status:409,body:{sessionId:'session',error:{code:'APPROVAL_REQUIRED'},approvalToken:'unconsumed-test',approvalSummary:`Confirmar ${ids.join(', ')} del 2030-01-01 al 2030-01-03.`,approvalPlan:{toolId:'hms.createMultiReservation',input:{roomIds:ids,checkIn:'2030-01-01',checkOut:'2030-01-03'}},approvalContext:{stay:{checkIn:'2030-01-01',checkOut:'2030-01-03',guests:4},selectedRoomIds:ids,roomOccupancy:[]},...overrides}}; }
test('exact C07 HITL completes in two turns and wrong final guests fails',()=>{const ok=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},boundary()]);assert.equal(ok.code,0);assert.equal(ok.calls.length,2);const wrong=boundary();wrong.body.approvalContext.stay.guests=2;const bad=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},wrong]);assert.equal(bad.code,1);assert.equal(bad.calls.length,2);});
test('only natural occupancy clarification permits a third turn, requiring 2+2',()=>{const request={body:{sessionId:'session',message:'¿Cómo distribuimos la ocupación en cada habitación?',outcome:'clarification',missing:['occupancy']}};const final=boundary();final.body.approvalContext.roomOccupancy=rooms.slice(0,2).map(x=>({roomId:x.id,guests:2}));const ok=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},request,final]);assert.equal(ok.code,0);assert.equal(ok.calls.length,3);assert.equal(ok.calls[2].body.message,'Dos en cada habitación.');const bad=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},request,boundary()]);assert.equal(bad.code,1);assert.equal(bad.calls.length,3);});
test('missing per-turn tail is supplemental for direct C06/C07 acceptance',()=>{for(const options of [{tailProof:false},{tailProof:false,tailPathMode:'missing'}]){const r=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},boundary()],options);assert.equal(r.code,0);assert.ok(r.report.transcript.every(item=>item.routeProof.status==='UNKNOWN_NOT_CAPTURED'));}});
test('direct receipt is required and deterministic fallback blocks dialogue and corpus acceptance',()=>{for(const script of ['scripts/r2.8-multi-room-dialogue.mjs','scripts/r2.8.4-llm-language-corpus.mjs']){for(const directRoute of [null,'deterministic_fallback']){const responses=script.includes('corpus')?corpusResponses():[{body:setup},boundary()];const r=run(script,responses,{tailProof:false,directRoute});assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.match(JSON.stringify(r.report),/direct validation receipt|baseline route receipt/);}}});
test('runner reports preserve approval presence but never approval-token values',()=>{const token='unconsumed-test';const dialogue=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},boundary()]);assert.equal(dialogue.code,0);assert.doesNotMatch(JSON.stringify(dialogue.report),new RegExp(token));assert.equal(dialogue.report.transcript[1].body.approvalTokenPresent,true);const corpusRun=run('scripts/r2.8.4-llm-language-corpus.mjs',corpusResponses());assert.equal(corpusRun.code,0);assert.doesNotMatch(JSON.stringify(corpusRun.report),new RegExp(token));assert.ok(JSON.stringify(corpusRun.report).includes('approvalTokenPresent'));});
test('captured envelopes without model events are supplemental for direct C06/C07 acceptance',()=>{const r=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup},boundary()],{tailRouteKind:'other'});assert.equal(r.code,0);assert.ok(r.report.transcript.every(item=>item.routeProof.status==='UNKNOWN_NOT_CAPTURED'));});
test('dialogue stops on captured fallback or wrong-version route proof',()=>{for(const options of [{tailRouteKind:'model_fallback'},{tailScriptVersionId:'wrong-version',versionId:'expected-version'}]){const r=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup}],options);assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.equal(r.report.transcript[0].routeProof.status,'CAPTURED_INVALID');assert.match(r.report.transcript[0].routeProof.reason,/fallback|Version mismatch/);}});
test('dialogue stops on corrupt, unreadable, or incomplete tail capture',()=>{for(const tailPathMode of ['corrupt','unreadable','incomplete']){const r=run('scripts/r2.8-multi-room-dialogue.mjs',[{body:setup}],{tailProof:false,tailPathMode});assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.equal(r.report.transcript[0].routeProof.status,'CAPTURED_INVALID');}});
function selectionClarification() { return {body:{sessionId:'session',outcome:'clarification',missing:['selection'],message:'Elegí una habitación disponible.'}}; }
function corpusApproval(numbers, guests) {
  const ids=numbers.map(number=>rooms.find(room=>room.roomNumber===number).id);
  const input=ids.length===1
    ? {roomId:ids[0],checkIn:'2030-01-01',checkOut:'2030-01-03'}
    : {roomIds:ids,checkIn:'2030-01-01',checkOut:'2030-01-03'};
  return boundary({approvalPlan:{toolId:ids.length===1?'hms.createReservation':'hms.createMultiReservation',input},approvalContext:{stay:{checkIn:'2030-01-01',checkOut:'2030-01-03',guests},selectedRoomIds:ids,roomOccupancy:[]}});
}
function corpusResponses() {
  return corpus.cases.flatMap(item=>{
    const guests=item.setupGuests??2;
    const availability={body:{...setup,data:{...setup.data,requestedGuests:guests}}};
    const initial=item.expected.roomNumbers ? corpusApproval(item.expected.roomNumbers,guests) : selectionClarification();
    const prior=item.priorSelection ? [corpusApproval([item.priorSelection],guests)] : [];
    const staleCheck=!item.expected.roomNumbers&&item.priorSelection ? [selectionClarification()] : [];
    return [availability,...prior,initial,...staleCheck];
  });
}
test('missing model telemetry cannot independently fail every L01-L15 direct corpus predicate',()=>{for(const options of [{tailProof:false},{tailProof:false,tailPathMode:'missing'},{tailRouteKind:'other'}]){const r=run('scripts/r2.8.4-llm-language-corpus.mjs',corpusResponses(),options);assert.equal(r.code,0);assert.deepEqual(r.report.results.map(item=>item.id),corpus.cases.map(item=>item.id));assert.ok(r.report.transcript.every(item=>item.pass&&item.turns.every(turn=>turn.routeProof.status==='UNKNOWN_NOT_CAPTURED')));}});
test('corpus stops on captured fallback or wrong-version route proof',()=>{for(const options of [{tailRouteKind:'model_fallback'},{tailScriptVersionId:'wrong-version',versionId:'expected-version'}]){const r=run('scripts/r2.8.4-llm-language-corpus.mjs',corpusResponses(),options);assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.equal(r.report.transcript[0].turns[0].routeProof.status,'CAPTURED_INVALID');assert.match(r.report.transcript[0].turns[0].routeProof.reason,/fallback|Version mismatch/);}});
test('corpus stops on corrupt, unreadable, or incomplete tail capture',()=>{for(const tailPathMode of ['corrupt','unreadable','incomplete']){const r=run('scripts/r2.8.4-llm-language-corpus.mjs',corpusResponses(),{tailProof:false,tailPathMode});assert.equal(r.code,1);assert.equal(r.calls.length,1);assert.equal(r.report.transcript[0].turns[0].routeProof.status,'CAPTURED_INVALID');}});
